"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 20:56:27.568863
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('product',
    sa.Column('product_code', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit_price_ex_tax', sa.Integer(), nullable=False),
    sa.Column('tax_class', sa.String(length=20), nullable=False),
    sa.CheckConstraint('unit_price_ex_tax >= 0', name='ck_product_price'),
    sa.PrimaryKeyConstraint('product_code')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('tax_rate',
    sa.Column('tax_rate_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_class', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('tax_rate_id')
    )
    op.create_index(op.f('ix_tax_rate_tax_class'), 'tax_rate', ['tax_class'], unique=False)
    op.create_table('promotion',
    sa.Column('promotion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=13), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('members_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_code'], ['product.product_code'], ),
    sa.PrimaryKeyConstraint('promotion_id')
    )
    op.create_index(op.f('ix_promotion_product_code'), 'promotion', ['product_code'], unique=False)
    op.create_table('transaction',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('transacted_at', sa.DateTime(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=20), nullable=True),
    sa.Column('total_ex_tax', sa.Integer(), nullable=False),
    sa.Column('total_discount', sa.Integer(), nullable=False),
    sa.Column('total_in_tax', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_detail',
    sa.Column('detail_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_code', sa.String(length=13), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('tax_class', sa.String(length=20), nullable=False),
    sa.Column('applied_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 99', name='ck_detail_qty'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.transaction_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_index(op.f('ix_transaction_detail_transaction_id'), 'transaction_detail', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_detail_transaction_id'), table_name='transaction_detail')
    op.drop_table('transaction_detail')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_promotion_product_code'), table_name='promotion')
    op.drop_table('promotion')
    op.drop_index(op.f('ix_tax_rate_tax_class'), table_name='tax_rate')
    op.drop_table('tax_rate')
    op.drop_table('staff')
    op.drop_table('product')
    op.drop_table('member')
    # ### end Alembic commands ###
